### ISSUE TITLE
guava 18.0 버전 build error

### ISSUE THREAD

**Issue by dmstjd1024** [java-book-study/TICKET-EXPEDITIONARY-FORCE#4]
#3 
제 컴퓨터 환경에선 guava 18.0 버전으로 돌리면 
![image](https://user-images.githubusercontent.com/54055200/94409383-0e8ea280-01b1-11eb-9d9e-67e628f6deff.png)
이런식으로 build error 뜨는데 다른분들은 어떻게 나오시나요?  아님 따로 해결방식을 알고계신 분 있나요?
(참고로 20.0버전에서는 정상작동합니다~)

**Comment by mintheon** [comment]
확인하였습니다. 데스크탑에서는 해당건 제대로 돌아갔던것 같은데, 노트북에서 돌리니 동일한 현상이 일어나네요!
해당건 swagger와 충돌이 일어나는것 같아요. 일단 현재 aop 사용하면서 구아바 참조가 두번 일어나는부분이 보여서 aop쪽에 같이 묶여서 사용한 18버전 삭제하고 공식 깃헙에서 사용하는 26버전으로 교체하도록 할게요!

**Comment by dmstjd1024** [comment]
굿굿 감사합니다!
